
services:
  mongo:
    image: mongo:latest
    container_name: mongo_gestor
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: ${MONGO_INITDB_NAME} 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
  
  mongo-express:
    image: mongo-express
    container_name: mongo_ui_gestor
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
    driver: local
